//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PateBookEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PB_USER()
        {
            this.PB_COMMENTS = new HashSet<PB_COMMENTS>();
            this.PB_FRIENDS = new HashSet<PB_FRIENDS>();
            this.PB_FRIENDS1 = new HashSet<PB_FRIENDS>();
            this.PB_LIKES = new HashSet<PB_LIKES>();
            this.PB_NOTIFICATION = new HashSet<PB_NOTIFICATION>();
            this.PB_NOTIFICATION1 = new HashSet<PB_NOTIFICATION>();
            this.PB_POSTS = new HashSet<PB_POSTS>();
            this.PB_POSTS1 = new HashSet<PB_POSTS>();
        }
    
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string SALT { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string GENDER { get; set; }
        public byte[] PROFILE_PIC { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public string ABOUT_ME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_COMMENTS> PB_COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_FRIENDS> PB_FRIENDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_FRIENDS> PB_FRIENDS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_LIKES> PB_LIKES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_NOTIFICATION> PB_NOTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_NOTIFICATION> PB_NOTIFICATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_POSTS> PB_POSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PB_POSTS> PB_POSTS1 { get; set; }
        public virtual PB_REF_COUNTRY PB_REF_COUNTRY { get; set; }
    }
}
