//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBookModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PasteBookEntities : DbContext
    {
        public PasteBookEntities()
            : base("name=PasteBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PB_COMMENTS> PB_COMMENTS { get; set; }
        public virtual DbSet<PB_FRIENDS> PB_FRIENDS { get; set; }
        public virtual DbSet<PB_LIKES> PB_LIKES { get; set; }
        public virtual DbSet<PB_NOTIFICATION> PB_NOTIFICATION { get; set; }
        public virtual DbSet<PB_POSTS> PB_POSTS { get; set; }
        public virtual DbSet<PB_REF_COUNTRY> PB_REF_COUNTRY { get; set; }
        public virtual DbSet<PB_USER> PB_USER { get; set; }
    
        public virtual ObjectResult<GetNewsFeedPost_Result> GetNewsFeedPost(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewsFeedPost_Result>("GetNewsFeedPost", userIDParameter);
        }
    
        public virtual ObjectResult<GetNewsFeed_Result> GetNewsFeed(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewsFeed_Result>("GetNewsFeed", userIDParameter);
        }
    }
}
