//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBookModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_LIKES
    {
        public int ID { get; set; }
        public int POST_ID { get; set; }
        public int LIKED_BY { get; set; }
    
        public virtual PB_USER PB_USER { get; set; }
        public virtual PB_POSTS PB_POSTS { get; set; }
    }
}
